# SPDX-License-Identifier: MIT
---
#
# Copyright 2025 bniladridas. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        files: '(\.dart|pubspec\.yaml)$'
        pass_filenames: false
      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        files: '(\.dart|pubspec\.yaml)$'
        pass_filenames: false
