# SPDX-License-Identifier: MIT
---
#
# Copyright 2026 Palmshed. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: 'Lint'
description: 'Run actionlint and yamllint on the repository'

runs:
  using: 'composite'
  steps:
    - uses: rhysd/actionlint@main
    - name: Install yamllint
      shell: bash
      run: |
        pip install yamllint
    - name: Run yamllint
      shell: bash
      run: yamllint .yamllint .github/workflows/*.yml .github/actions/**/*.yml pubspec.yaml
