# SPDX-License-Identifier: MIT
---
#
# Copyright 2026 Palmshed. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Palmshed'
    steps:
      - id: app-token
        name: Create Via app token
        uses: actions/create-github-app-token@v2
        with:
          client-id: ${{ secrets.VIA_APP_CLIENT_ID }}
          private-key: ${{ secrets.VIA_APP_PRIVATE_KEY }}
          permission-actions: write
          permission-issues: write
          permission-contents: read

      - uses: libnudget/stale@v1
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
