# SPDX-License-Identifier: MIT
---
#
# Copyright 2026 Palmshed. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
  schedule:
    - cron: "0 4 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Palmshed'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - id: app-token
        name: Create Via app token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.VIA_APP_ID }}
          private-key: ${{ secrets.VIA_APP_PRIVATE_KEY }}
          permission-issues: write
          permission-contents: read

      - name: Sync repository labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          yaml-file: .github/labels.yml
          dry-run: false
          skip-delete: false
