# SPDX-License-Identifier: MIT
---
#
# Copyright 2026 Palmshed. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Palmshed'

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint
