# SPDX-License-Identifier: MIT
---
#
# Copyright 2026 bniladridas. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: website version

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: write

jobs:
  update-version:
    name: website version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: count commits
        id: count
        run: |
          COMMITS=$(git rev-list --count HEAD)
          echo "count=$COMMITS" >> "$GITHUB_OUTPUT"

      - name: update version
        run: |
          echo "1.0.${{ steps.count.outputs.count }}" > WEBSITE-VERSION
          cat WEBSITE-VERSION

      - name: commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update website version"
          file_pattern: WEBSITE-VERSION
